export const ErrorCodes = {
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CAMPAIGN_ENDED: 'CAMPAIGN_ENDED',
  ALREADY_JOINED: 'ALREADY_JOINED',
  ALREADY_SUBMITTED: 'ALREADY_SUBMITTED',
  INVALID_WALLET: 'INVALID_WALLET',
  TASK_LOCKED: 'TASK_LOCKED',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  CONFLICT: 'CONFLICT',
  BAD_REQUEST: 'BAD_REQUEST',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
